import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession } from "@inrupt/solid-ui-react";

import useProfile from '../hooks/useProfile'
import { useEffect } from 'react';
const Home: NextPage = () => {
  const { session } = useSession();
// const {name,webId,storageUrl,error} = useProfile("")

useEffect(() => {

}, [ ]);

  return (
    <div className={styles.container}>
   
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
                      <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
     <h1>Home Screen Here! </h1>
      </main>
    </div>
  )
}

export default Home
