import React, { useEffect } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

function Home() {
  // ..const {name,webId,storageUrl,error} = useProfile("")

  useEffect(() => {}, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Home Screen Here! </h1>
      </main>
    </div>
  );
}

export default Home;
